import Head from "next/head";
import Image from "next/image";
import Link from "next/link";
import NavPage from "../../components/all/nav-page";
import ServiceCard from "../../components/services/serviceCard";
import ServiceImage from "../../components/services/serviceImage";
import ServiceTitle from "../../components/services/serviceTitle";
import Container from "../../components/shared/composers/container";
import { motion, MotionConfig } from "framer-motion";
import { useState } from "react";
const Services = () => {
  const [data, setData] = useState({ name: "" });
  const [services, setServices] = useState([
    {
      id: "creation-de-contenu",
      title: "Création de contenu",
      subtitle: "UX/UI Design & Mobile Application Development",
    },
    {
      id: "website",
      title: "Web Site",
      subtitle: "UX/UI Design & Mobile Application Development",
    },
  ]);

  return (
    <NavPage current='Nos services'>
      {" "}
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
        <link rel='preconnect' href='https://fonts.googleapis.com' />
        <link rel='preconnect' href='https://fonts.gstatic.com' crossorigin />
        <link
          href='https://fonts.googleapis.com/css2?family=Poppins:wght@100;200;300;400;500;600;700;800;900&display=swap'
          rel='stylesheet'
        />
      </Head>
      <main className='bg-[#FFFAF5]  pt-28'>
        <div className='absolute inset-0 flex items-center justify-center'></div>
        <ServiceTitle />{" "}
        <Container className='absolute '>
          <Image
            src='/assets/background/vector.svg'
            alt='Picture of the author'
            width={500}
            height={800}
            className='absolute'
          />
        </Container>
        <Container className='mx-5 relative text-center space-y-8 mt-6'>
          {services.map((service) => (
            <Link
              href={{
                pathname: "services/[id]",
                query: {
                  id: service.id,
                },
              }}
              as={`services/${service.id}`}
            >
              <a>
                <ServiceCard serviceName={service.title} service={service} />
              </a>
            </Link>
          ))}

          <Link href='/services/website'>
            <a>
              <ServiceCard serviceName={"Web Design"} />
            </a>
          </Link>
        </Container>
        <ServiceImage />
        <Container className='absolute mb-24'>
          <Image
            src='/assets/background/vector.svg'
            alt='Picture of the author'
            width={500}
            height={800}
            className='absolute'
          />
        </Container>
        <Container className='mx-5 relative text-center space-y-8 mt-6'>
          <Link href='/services/marketing'>
            <a>
              <ServiceCard serviceName={"Marketing"} />
            </a>
          </Link>
          <Link href='/services/website'>
            <a>
              <ServiceCard serviceName={"Web Design"} />
            </a>
          </Link>
          <Link href='/services/website'>
            <a>
              <ServiceCard serviceName={"Web Design"} />
            </a>
          </Link>
        </Container>{" "}
      </main>
    </NavPage>
  );
};
export default Services;
