// This file is generated by Slice Machine. Update with care!

import Blog from './Blog';
import BlogTitle from './BlogTitle';
import BlogsTest from './BlogsTest';

export {
	Blog,
	BlogTitle,
	BlogsTest,
};

export const components = {
	blog: Blog,
	blog_title: BlogTitle,
	blogs_test: BlogsTest,
};
