// Code generated by Slice Machine. DO NOT EDIT.

import Blog from './Blog';
import BlogDescription from './BlogDescription';
import BlogTitle from './BlogTitle';
import BlogsTest from './BlogsTest';

export {
	Blog,
	BlogDescription,
	BlogTitle,
	BlogsTest,
};

export const components = {
	blog: Blog,
	blog_description: BlogDescription,
	blog_title: BlogTitle,
	blogs_test: BlogsTest,
};
