import Head from "next/head";
import NavPage from "../../../components/all/nav-page";
import ContactHero from "../../../components/contact/ContactHero";
import ContactTitle from "../../../components/contact/contactTitle";
import ProgressBar from "../../../components/contact/progressBar";

const Contact = () => {
  return (
    <NavPage current='Contact'>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
        <link rel='preconnect' href='https://fonts.googleapis.com' />
        <link rel='preconnect' href='https://fonts.gstatic.com' crossorigin />
        <link
          href='https://fonts.googleapis.com/css2?family=Poppins:wght@100;200;300;400;500;600;700;800;900&display=swap'
          rel='stylesheet'
        />
      </Head>
      <main className='bg-[#FFFAF5]  pt-28'>
        <ContactTitle />
        <ProgressBar step={2} total={4} />
        <ContactHero />
      </main>
    </NavPage>
  );
};
export default Contact;
