import Head from "next/head";
import Image from "next/image";
import Link from "next/link";
import NavPage from "../../components/all/nav-page";
import ServiceCard from "../../components/services/serviceCard";
import ServiceImage from "../../components/services/serviceImage";
import ServiceTitle from "../../components/services/serviceTitle";
import Container from "../../components/shared/composers/container";
import { motion, MotionConfig } from "framer-motion";
import { useState } from "react";
import MotionLeft from "../../components/shared/composers/motion-CardLeft";
const Services = () => {
  const [data, setData] = useState({ name: "" });
  const [services, setServices] = useState([
    {
      id: "creation-de-contenu",
      title: "Création de contenu",
      subtitle: "UX/UI Design & Mobile Application Development",
      src: "/assets/logo/Blog.svg",
    },
    {
      id: "website",
      title: "Web Site",
      subtitle: "UX/UI Design & Mobile Application Development",
      src: "/assets/logo/Computer.svg",
    },
  ]);
  const [services2, setServices2] = useState([
    {
      id: "social-media",
      title: "Social média",
      subtitle: "UX/UI Design & Mobile Application Development",
      src: "/assets/logo/Blog.svg",
    },
    {
      id: "referencement",
      title: "Référencement web",
      subtitle: "UX/UI Design & Mobile Application Development",
      src: "/assets/logo/Computer.svg",
    },
  ]);
  return (
    <NavPage current='Services'>
      {" "}
      <Head>
        <title>Listri Agence Digitale</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.svg' />
        <link rel='preconnect' href='https://fonts.googleapis.com' />
        <link rel='preconnect' href='https://fonts.gstatic.com' crossOrigin />
        <link
          href='https://fonts.googleapis.com/css2?family=Poppins:wght@100;200;300;400;500;600;700;800;900&display=swap'
          rel='stylesheet'
        />
      </Head>
      <main className='bg-[#FFFAF5]  py-28 '>
        <div className='absolute inset-0 flex items-center justify-center'></div>
        <ServiceTitle />{" "}
        <Container className='mx-5 relative text-center space-y-8 mt-6'>
          {services.map((service, i) => (
            <MotionLeft
              initial='hidden'
              animate='visible'
              transition={{ duration: 0.8 }}
              key={i}
            >
              <Link
                href={{
                  pathname: "services/[id]",
                  query: {
                    id: service.id,
                  },
                }}
                as={`/services/${service.id}`}
                passHref
              >
                <a>
                  <ServiceCard
                    key={service.id}
                    serviceName={service.title}
                    service={service}
                    src={service.src}
                  />
                </a>
              </Link>
            </MotionLeft>
          ))}
        </Container>
        <ServiceImage />
        <Container className='mx-5 relative text-center space-y-8'>
          {services2.map((service, i) => (
            <MotionLeft
              initial='hidden'
              animate='visible'
              transition={{ duration: 1 }}
              key={i}
            >
              <Link
                href={{
                  pathname: "services/[id]",
                  query: {
                    id: service.id,
                  },
                }}
                as={`/services/${service.id}`}
                passHref
              >
                <a>
                  <ServiceCard
                    key={service.id}
                    serviceName={service.title}
                    service={service}
                    src={service.src}
                  />
                </a>
              </Link>{" "}
            </MotionLeft>
          ))}
        </Container>{" "}
      </main>
    </NavPage>
  );
};
export default Services;
