import Head from "next/head";
import Container from "../../components/shared/composers/container";

export default function Julien() {
  return (
    <Container>
      <Head>
        <title>Listri Agence Digitale</title>
        <meta
          name='Listri a pour objectif de vous aider dans votre démarche digitale. Du site web jusqu’à vos réseaux sociaux en passant par le référencement, nous sommes là pour vous rendre visible face à votre audience. '
          content='Generated by Listri'
        />
        <link rel='shortcut icon' href='/favicon.ico' />
        <link rel='preconnect' href='https://fonts.googleapis.com' />
        <link rel='preconnect' href='https://fonts.gstatic.com' crossOrigin />
        <link
          href='https://fonts.googleapis.com/css2?family=Poppins:wght@100;200;300;400;500;600;700;800;900&display=swap'
          rel='stylesheet'
        />
      </Head>

      <main className='bg-[#FFFAF5] pt-28  text-[#37474F]'>
        <Container>
          <p>{"hello i'm julien "}</p>
        </Container>
      </main>
    </Container>
  );
}
