import Head from "next/head";
import Image from "next/image";
import NavPage from "../components/all/nav-page";
export default function Home() {
  return (
    <NavPage current='Home'>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      {/* <main>
        <h1 className='text-3xl font-bold underline bg-red-300'>
          Hello world!
        </h1>
      </main> */}

      <footer></footer>
    </NavPage>
  );
}
