import Head from "next/head";
import Link from "next/link";
import NavPage from "../../components/all/nav-page";
import Container from "../../components/shared/composers/container";
import CardBlog from "./[uid]";
import { createClient } from "../../../prismicio";
import Blog from "./[uid]";
import { data } from "autoprefixer";
import { BlogSlices, BlogsTest, TitleBlog } from "../../../slices";
import * as prismicH from "@prismicio/helpers";
import { SliceZone, PrismicText, PrismicRichText } from "@prismicio/react";
import { components } from "../../../slices";
import Flex from "../../components/shared/composers/flex";
import Image from "next/image";
import TitlePage from "../../components/all/titlePage";

const Blogs = ({ blogs, BlogTitle }) => {
  console.log(blogs, "blogs");
  const titlepageprops = {
    title: " Blog",
    subtitle: "L’actualité & les ressources ",
    description:
      "Tout ce qu’il vous faut pour découvrir et comprendre le monde du digital 3.0 Restez à jour avec listri",
  };

  return (
    <NavPage current='Blog'>
      <Head>
        <title>Listri Agence Digitale</title>
        <meta
          name='Listri a pour objectif de vous aider dans votre démarche digitale. Du site web jusqu’à vos réseaux sociaux en passant par le référencement, nous sommes là pour vous rendre visible face à votre audience. '
          content='Generated by Listri'
        />
        <link rel='icon' href='/favicon.svg' />
        <link rel='preconnect' href='https://fonts.googleapis.com' />
        <link rel='preconnect' href='https://fonts.gstatic.com' crossOrigin />
        <link
          href='https://fonts.googleapis.com/css2?family=Poppins:wght@100;200;300;400;500;600;700;800;900&display=swap'
          rel='stylesheet'
        />
      </Head>

      <main className='bg-[#FFFAF5]  pt-28 '>
        <Container className='mb-10  '>
          <TitlePage
            title={titlepageprops.title}
            subtitle={titlepageprops.subtitle}
            description={titlepageprops.description}
          />
          <Flex type='row' justify='center' className=' '>
            <ul className='md:flex md:flex-row md:flex-wrap md:justify-center'>
              {" "}
              {blogs.map((blog) => (
                <Link href={`/blogs/${blog.uid}`} key={blog.uid} passHref>
                  <a key={blog.uid}>
                    <Container className=' rounded-tl-[10px] rounded-br-[10px] rounded-tr-[50px] rounded-bl-[50px]  m-5 mb-20 min-h-[290px] relative '>
                      <Container className='absolute w-fit'>
                        <Image
                          src={blog.data.slices[0].items[0].img.url}
                          alt='Picture of the author'
                          width={350}
                          height={300}
                          className='rounded-tl-[20px] rounded-br-[20px] rounded-tr-[80px] rounded-bl-[80px]'
                        />
                        <Container className='h-[300px] w-[350px] bg-gradient-to-t from-black/80 absolute m-auto rounded-tl-[20px] rounded-br-[20px] rounded-tr-[80px] rounded-bl-[80px] shadow-ServiceCard' />
                      </Container>
                      <Flex
                        type='col'
                        justify='end'
                        align='center'
                        className='z-10 mb-6'
                      >
                        <Container className=' text-[#FFFAF5] text-[20px] font-medium text-center w-[350px]'>
                          {blog.data.slices[0].items[0].title[0].text}{" "}
                        </Container>

                        <Container className=' text-[#FFFAF5] text-[17px] font-light text-right w-full   max-w-[300px]  '>
                          {"suite ..."}
                        </Container>
                      </Flex>
                    </Container>
                  </a>
                </Link>
              ))}
            </ul>{" "}
          </Flex>
        </Container>
      </main>
    </NavPage>
  );
};
export default Blogs;

export async function getStaticProps({ previewData }) {
  const client = createClient({ previewData });

  const blogs = await client.getAllByType("BlogPost", {
    orderings: [
      { field: "my.article.publishDate", direction: "desc" },
      { field: "document.first_publication_date", direction: "desc" },
    ],
  });

  return {
    props: {
      blogs,
    },
  };
}
